spring:
  application:
    name: UsersApplication
  jpa:
    show-sql: true
#  sql:
#    init:
#      mode: always
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  datasource:
#    url: jdbc:postgresql://172.17.0.2:5432/postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
